### PR TITLE
Use cubic spline for initial guess

### PR DESCRIPTION
**Pull request by bruingineer**
use wpi spline generator to create the initial guess translation. heading is interpolated separately between each waypoint and initial guess point.

### CODE REVIEW

**Review by spacey-sooty — COMMENTED** [review]
I dont think this should manually copy in Eigen or wpimath....

**Comment by calcmogul** [comment]
Instead, it could fetch allwpilib via FetchContent and pass the following:
```cmake
    -DUSE_SYSTEM_EIGEN=ON \
    -DUSE_SYSTEM_FMTLIB=ON \
    -DWITH_JAVA=OFF \
    -DWITH_CSCORE=OFF \
    -DWITH_NTCORE=OFF \
    -DWITH_WPIMATH=ON \
    -DWITH_WPILIB=OFF \
    -DWITH_TESTS=OFF \
    -DWITH_GUI=OFF \
    -DWITH_SIMULATION_MODULES=OFF \
```

**Comment by calcmogul** [comment]
I tried the thing I suggested, and WPILib's CMake setup is kinda broken. Here's the changes I had to make to WPILib:
```diff
diff --git a/wpimath/CMakeLists.txt b/wpimath/CMakeLists.txt
index a22ffc0b8..c7a99729c 100644
--- a/wpimath/CMakeLists.txt
+++ b/wpimath/CMakeLists.txt
@@ -200,6 +200,7 @@ target_include_directories(
 )
 
 install(TARGETS wpimath EXPORT wpimath)
+export(TARGETS wpimath FILE wpimath.cmake NAMESPACE wpimath::)
 
 configure_file(wpimath-config.cmake.in ${WPILIB_BINARY_DIR}/wpimath-config.cmake)
 install(FILES ${WPILIB_BINARY_DIR}/wpimath-config.cmake DESTINATION share/wpimath)
diff --git a/wpiutil/CMakeLists.txt b/wpiutil/CMakeLists.txt
index 4caa3521b..e01203f6c 100644
--- a/wpiutil/CMakeLists.txt
+++ b/wpiutil/CMakeLists.txt
@@ -258,6 +258,7 @@ target_include_directories(
 )
 
 install(TARGETS wpiutil EXPORT wpiutil)
+export(TARGETS wpiutil FILE wpiutil.cmake NAMESPACE wpiutil::)
 
 configure_file(wpiutil-config.cmake.in ${WPILIB_BINARY_DIR}/wpiutil-config.cmake)
 install(FILES ${WPILIB_BINARY_DIR}/wpiutil-config.cmake DESTINATION share/wpiutil)
```
Here's the TrajoptLib CMake changes:
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 02e4ad4..9598e9e 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -15,6 +15,9 @@ set(CMAKE_MODULE_PATH
     "${CMAKE_CURRENT_SOURCE_DIR}/cmake/modules"
 )
 
+# Allow overriding options in parent projects
+cmake_policy(SET CMP0077 NEW)
+
 project(TrajoptLib LANGUAGES CXX)
 
 # Use, i.e. don't skip the full RPATH for the build tree
@@ -146,6 +149,23 @@ elseif(${OPTIMIZER_BACKEND} STREQUAL "sleipnir")
     target_link_libraries(TrajoptLib PRIVATE Sleipnir)
 endif()
 
+# wpimath dependency
+set(WITH_CSCORE OFF CACHE INTERNAL "With CSCore")
+set(WITH_GUI OFF CACHE INTERNAL "With GUI")
+set(WITH_JAVA OFF CACHE INTERNAL "With Java")
+set(WITH_NTCORE OFF CACHE INTERNAL "With NTCore")
+set(WITH_SIMULATION_MODULES OFF CACHE INTERNAL "With Simulation Modules")
+set(WITH_TESTS OFF CACHE INTERNAL "With Tests")
+set(WITH_WPIMATH ON CACHE INTERNAL "With WPIMath")
+set(WITH_WPILIB OFF CACHE INTERNAL "With WPILib")
+fetchcontent_declare(
+    wpilib
+    GIT_REPOSITORY https://github.com/wpilibsuite/allwpilib.git
+    GIT_TAG v2024.3.2
+)
+fetchcontent_makeavailable(wpilib)
+target_link_libraries(TrajoptLib PRIVATE wpimath)
+
 target_include_directories(
     TrajoptLib
     PUBLIC
```
I changed the fetchcontent target to a `file://` repo and local commit hash for testing. wpimath doesn't seem to export Eigen's include paths.
```bash
In file included from /home/tav/git/TrajoptLib/include/frc/geometry/Transform2d.h:9,
                 from /home/tav/git/TrajoptLib/include/frc/geometry/Pose2d.h:13,
                 from /home/tav/git/TrajoptLib/src/optimization/TrajoptUtil.inc:14,
                 from /home/tav/git/TrajoptLib/src/optimization/TrajoptUtil.h:113,
                 from /home/tav/git/TrajoptLib/src/optimization/HolonomicTrajoptUtil.h:8,
                 from /home/tav/git/TrajoptLib/src/optimization/SwerveTrajoptUtil.h:8,
                 from /home/tav/git/TrajoptLib/test/src/SwerveTrajoptUtilTest.cpp:11:
/home/tav/git/TrajoptLib/include/frc/geometry/Translation2d.h:10:10: fatal error: Eigen/Core: No such file or directory
   10 | #include <Eigen/Core>
      |          ^~~~~~~~~~~~
compilation terminated.
```

**Comment by calcmogul** [comment]
https://github.com/bruingineer/TrajoptLib/pull/1

**Comment by calcmogul** [comment]
If I recall correctly, WPILib can't build with MinGW on Windows, which means the CasADi builds will always be broken.

**Comment by spacey-sooty** [comment]
> If I recall correctly, WPILib can't build with MinGW on Windows, which means the CasADi builds will always be broken.

How hard is this to work around?What's stopping CasADI from being built with MSVC?

**Comment by calcmogul** [comment]
With regard to the merge conflicts, the linear initial guess generator moved to https://github.com/SleipnirGroup/TrajoptLib/blob/main/include/trajopt/util/GenerateLinearInitialGuess.hpp, so this PR can mirror that structure.

**Comment by calcmogul** [comment]
TrajoptLib has moved to a subfolder within SleipnirGroup/Choreo. The changes here should be merged into SleipnirGroup/Choreo#478.

**Pull request closed without merging**
